#pragma once

// 本文件由 assets/poses/*.webp 自动生成，禁止手改。
// 93 张立绘：统一 256x256 webp（VP8X）。

namespace whalepet::core {

struct PoseEntry {
    const char *key;   // 语义 pose 名（状态机使用）
    const char *file;  // 资源文件基名，路径 = :/poses/<file>.webp
};

inline constexpr PoseEntry kPoses[] = {
    {"home-peek", "dsh-whale-home-peek"},
    {"home-bottom", "dsh-whale-home-bottom"},
    {"settings-peek", "dsh-whale-settings-peek"},
    {"abstract", "dsh-whale-state-abstract"},
    {"achievement", "dsh-whale-state-achievement"},
    {"afk", "dsh-whale-state-afk"},
    {"angry", "dsh-whale-state-angry"},
    {"balance-low", "dsh-whale-state-balance-low"},
    {"blush", "dsh-whale-state-blush"},
    {"bold", "dsh-whale-state-bold"},
    {"celebrate", "dsh-whale-state-celebrate"},
    {"cool-shades", "dsh-whale-state-cool-shades"},
    {"curious", "dsh-whale-state-curious"},
    {"daily-coffee", "dsh-whale-state-daily-coffee"},
    {"daily-cooking", "dsh-whale-state-daily-cooking"},
    {"daily-done", "dsh-whale-state-daily-done"},
    {"daily-eat", "dsh-whale-state-daily-eat"},
    {"daily-fishing", "dsh-whale-state-daily-fishing"},
    {"daily-gaming", "dsh-whale-state-daily-gaming"},
    {"daily-melt", "dsh-whale-state-daily-melt"},
    {"daily-painting", "dsh-whale-state-daily-painting"},
    {"daily-pajama", "dsh-whale-state-daily-pajama"},
    {"daily-picnic", "dsh-whale-state-daily-picnic"},
    {"daily-shower", "dsh-whale-state-daily-shower"},
    {"daily-stretch", "dsh-whale-state-daily-stretch"},
    {"eat", "dsh-whale-state-eat"},
    {"failure", "dsh-whale-state-failure"},
    {"festival-christmas", "dsh-whale-state-festival-christmas"},
    {"festival-halloween", "dsh-whale-state-festival-halloween"},
    {"festival-mid-autumn", "dsh-whale-state-festival-mid-autumn"},
    {"festival-spring", "dsh-whale-state-festival-spring"},
    {"game-cheat", "dsh-whale-state-game-cheat"},
    {"game-happy", "dsh-whale-state-game-happy"},
    {"game-lose", "dsh-whale-state-game-lose"},
    {"game-think", "dsh-whale-state-game-think"},
    {"game-win", "dsh-whale-state-game-win"},
    {"greet", "dsh-whale-state-greet"},
    {"idle-cute", "dsh-whale-state-idle-cute"},
    {"levelup", "dsh-whale-state-levelup"},
    {"meme-broke", "dsh-whale-state-meme-broke"},
    {"meme-cry", "dsh-whale-state-meme-cry"},
    {"meme-doge", "dsh-whale-state-meme-doge"},
    {"meme-doubt", "dsh-whale-state-meme-doubt"},
    {"meme-heart", "dsh-whale-state-meme-heart"},
    {"meme-kyun", "dsh-whale-state-meme-kyun"},
    {"meme-music", "dsh-whale-state-meme-music"},
    {"meme-no", "dsh-whale-state-meme-no"},
    {"meme-ojisan", "dsh-whale-state-meme-ojisan"},
    {"meme-omg", "dsh-whale-state-meme-omg"},
    {"meme-peace", "dsh-whale-state-meme-peace"},
    {"meme-shock", "dsh-whale-state-meme-shock"},
    {"meme-sike", "dsh-whale-state-meme-sike"},
    {"meme-smile-pain", "dsh-whale-state-meme-smile-pain"},
    {"meme-smug", "dsh-whale-state-meme-smug"},
    {"meme-wakuwaku", "dsh-whale-state-meme-wakuwaku"},
    {"meme-worship", "dsh-whale-state-meme-worship"},
    {"meme-yes", "dsh-whale-state-meme-yes"},
    {"night", "dsh-whale-state-night"},
    {"pick-up", "dsh-whale-state-pick-up"},
    {"react-belly", "dsh-whale-state-react-belly"},
    {"react-head", "dsh-whale-state-react-head"},
    {"react-tail", "dsh-whale-state-react-tail"},
    {"running", "dsh-whale-state-running"},
    {"sleep", "dsh-whale-state-sleep"},
    {"star", "dsh-whale-state-star"},
    {"success", "dsh-whale-state-success"},
    {"sweep", "dsh-whale-state-sweep"},
    {"tail-swing", "dsh-whale-state-tail-swing"},
    {"teasing", "dsh-whale-state-teasing"},
    {"thinking", "dsh-whale-state-thinking"},
    {"tool", "dsh-whale-state-tool"},
    {"valentine", "dsh-whale-state-valentine"},
    {"waiting", "dsh-whale-state-waiting"},
    {"weather-cold", "dsh-whale-state-weather-cold"},
    {"weather-rain-happy", "dsh-whale-state-weather-rain-happy"},
    {"weather-snow", "dsh-whale-state-weather-snow"},
    {"weather-thunder", "dsh-whale-state-weather-thunder"},
    {"weather-umbrella", "dsh-whale-state-weather-umbrella"},
    {"wink", "dsh-whale-state-wink"},
    {"work-boss", "dsh-whale-state-work-boss"},
    {"work-celebrate", "dsh-whale-state-work-celebrate"},
    {"work-deadline", "dsh-whale-state-work-deadline"},
    {"work-debug", "dsh-whale-state-work-debug"},
    {"work-deploy", "dsh-whale-state-work-deploy"},
    {"work-idea", "dsh-whale-state-work-idea"},
    {"work-meeting", "dsh-whale-state-work-meeting"},
    {"work-pat", "dsh-whale-state-work-pat"},
    {"work-ram", "dsh-whale-state-work-ram"},
    {"work-review", "dsh-whale-state-work-review"},
    {"work-slack", "dsh-whale-state-work-slack"},
    {"work-slack-phone", "dsh-whale-state-work-slack-phone"},
    {"work-sleep", "dsh-whale-state-work-sleep"},
    {"workbench-peek", "dsh-whale-workbench-peek"},
};

inline constexpr int kPoseCount = 93;

} // namespace whalepet::core
