# ---------------------------------------------------------------------------
# 模块：Executables —— 可执行目标定义与产物落盘规则
# 职责：定义工程的可执行目标并应用输出目录 / 调试符号策略：
#   WhalePet      主程序（WIN32 GUI 子系统）
#   whalepet-mcp  MCP stdio 桥接进程（控制台子系统）
# 依赖：Libraries（whalepet_view / whalepet_contextapi）、
#       OutputLayout（WHALEPET_DEPLOY_DIR / WHALEPET_DIST_DIR / WHALEPET_PACKAGE）。
# 说明：由顶层通过 include() 引入，与顶层共享同一变量作用域。
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# 主程序
# ---------------------------------------------------------------------------
qt_add_executable(WhalePet WIN32
    src/app/main.cpp
)
target_link_libraries(WhalePet PRIVATE whalepet_view)

# Windows 可执行文件图标（资源管理器 / 任务栏 / 开始菜单快捷方式）。
# 用 CMake 生成 .rc 并写入图标的**绝对路径**：rc.exe 对 .rc 内相对路径的解析
# 取决于调用时的工作目录，绝对路径可避免「静默用了默认图标」这类问题。
if(WIN32)
    set(_whalepet_icon "${CMAKE_CURRENT_SOURCE_DIR}/assets/icon/whalepet.ico")
    if(NOT EXISTS "${_whalepet_icon}")
        message(FATAL_ERROR "未找到应用图标: ${_whalepet_icon}")
    endif()
    file(TO_CMAKE_PATH "${_whalepet_icon}" _whalepet_icon_posix)
    set(_whalepet_icon_rc "${CMAKE_CURRENT_BINARY_DIR}/whalepet_app_icon.rc")
    # 保持纯 ASCII：rc.exe 不按 UTF-8 解析（与 scripts/*.ps1 的 ASCII 约定同源）
    file(WRITE "${_whalepet_icon_rc}"
        "// Generated by CMakeLists.txt - do not edit: Windows executable icon\n"
        "IDI_ICON1 ICON \"${_whalepet_icon_posix}\"\n")
    target_sources(WhalePet PRIVATE "${_whalepet_icon_rc}")
endif()

# 产物落盘策略（目录与开关来自 OutputLayout 模块）：
if(WHALEPET_PACKAGE)
    set_target_properties(WhalePet PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${WHALEPET_DIST_DIR}"
    )
else()
    # Release 版同时产出调试符号（PDB 落在部署目录）：
    #   用户侧的崩溃分析统一用 Qt Creator 打开 Release 产物（见 docs/README.md §六），
    #   没有同目录 PDB 就只能看到地址。`/Zi` 只增加调试信息，**不改变 /O2 优化**，
    #   也不涉及 debug/release 运行库混用（与 `TRAP-P2-008` 的混用问题无关）。
    set_target_properties(WhalePet PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${WHALEPET_DEPLOY_DIR}"
        PDB_OUTPUT_DIRECTORY_RELEASE "${WHALEPET_DEPLOY_DIR}"
    )
    target_compile_options(WhalePet PRIVATE $<$<CONFIG:Release>:/Zi>)
    target_link_options(WhalePet PRIVATE $<$<CONFIG:Release>:/DEBUG>)
endif()

# ---------------------------------------------------------------------------
# P7.2：MCP stdio 桥接进程（控制台）
#   —— 主程序是 WIN32 GUI 子系统，没有可用的 stdin/stdout，无法直接当 MCP stdio
#      Server；本进程把 MCP 客户端的 stdin/stdout 字节转发到主程序的命名管道
#     （LocalPipeTransport），自身不含业务逻辑。见 docs/CONTEXT-API.md §4、
#     docs/packages.md §2.1。
#   —— 控制台子系统（**故意不加 WIN32**）：必须保留可用的 stdin/stdout。
#   —— 与 WhalePet.exe 同目录产出，随包分发（安装/卸载对应关系见 docs/packages.md §5）。
# ---------------------------------------------------------------------------
qt_add_executable(whalepet-mcp
    src/app/mcp_bridge_main.cpp
)
# 复用 kDefaultContextPipeName（管道名唯一约定源）与 contextapi 的 include 路径
target_link_libraries(whalepet-mcp PRIVATE whalepet_contextapi)

if(WHALEPET_PACKAGE)
    set_target_properties(whalepet-mcp PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${WHALEPET_DIST_DIR}"
    )
else()
    set_target_properties(whalepet-mcp PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${WHALEPET_DEPLOY_DIR}"
        PDB_OUTPUT_DIRECTORY_RELEASE "${WHALEPET_DEPLOY_DIR}"
    )
    target_compile_options(whalepet-mcp PRIVATE $<$<CONFIG:Release>:/Zi>)
    target_link_options(whalepet-mcp PRIVATE $<$<CONFIG:Release>:/DEBUG>)
endif()
